jobs:
  - id: beno_cto
    achievements:
      - Established 5 years engineering vision influenced by the rise of ChatGPT and LLMs, and executed the first phase by releasing a ChatGPT-powered chat resulting in 10% increase in sales leads.
      - Successfully scaled the engineering organization to three engineering teams (25+ engineers), establishing clear objectives and key results (OKRs) and product roadmaps for each team.
      - Reduced department cost by lowering AWS monthly bill by 21% between 2024-Q1 and Q2, optimizing SaaS cost, and augmenting team with lower cost members through effective internship program.
      - Cultivated new leadership from (IC) Individual Contributors ranks resulting in promoting one EM (Engineering Manager) internally and preparing two senior engineers for future EM positions.
      - Influenced directors and employees in various departments (content creation, HR, operations) by the mantra "AI is the new Excel" and showcasing effective use cases.

  - id: beno_em
    achievements:
      - Significantly grew the engineering department from 5 to 20 engineers while simultaneously reducing annual turnover from 70% to 6% by expanding remote hiring into five countries.
      - Enhanced agile methodology by implementing Kanban Flight Levels and advanced forecasting techniques using Cycle Time and Monte Carlo simulation.
      - Led the Front-end Applications team in improving deployment frequency from twice a month to four times a week by introducing a shared UI Kit and streamlining the design hand-off process.
      - Led the Mobile Applications team in improving deployment frequency from once a month to twice a week by introducing Kotlin Multiplatform Mobile (KMM) and implementing a CI/CD pipeline.
      - Defined comprehensive IT processes, including job descriptions, roles, salary scales, a [skill levels framework](https://app.progressionapp.com/teams/beno-engineering/framework), a recruitment process, and performance reviews.

  - id: beno_lead
    achievements:
      - Pioneered advanced back-end development practices by implementing API-breaking change detection and client code generation.
      - Established comprehensive technical documentation for the system's architecture using C4 Modeling with Structurizr, adhering to the principles of "diagram as code."

  - id: roamworks_arch
    achievements:
      - Led a small team to build IoT applications powered by Microsoft and Azure technology stack.

  - id: roamworks_bi
    achievements: []

  - id: fujitsu
    achievements: []

skill_groups:
  - category: Technical
    skills: REST, AWS, Functional Programming, OOP, <span class="iconify" data-icon="vscode-icons:file-type-angular"></span> Angular, <span class="iconify" data-icon="devicon:spring"></span> Spring, SQL
  - category: Managerial
    skills: Leadership, Engineering Management, Mentoring, Coaching
