jobs:
  - id: beno_cto
    achievements:
      - Led maintenance of centralized architecture following architecture-as-code using C4 (Structurizr), enabling ARDs, architecture review/audit as PR, and co-editing architecture with AI
      - Led implementation of microservice for ERP (Odoo) integration using Spring Cloud Stream and Web Hooks, resulting in streamlined business operations with high availability
      - Designed architecture enabling multilingual content and SEO using headless CMS (Strapi) and translation platform (Weblate), resulting in 29% improvement in keyword positioning
      - Led frontend engineers and QA in optimizing web app through SSR, SSG, CDN, and hydration while implementing QA gates, resulting in load times under 2.5 seconds
      - Implemented a microservice for AI chat using NestJS, OpenAI, and AWS services, utilizing minimal budget and university interns

  - id: beno_em
    achievements:
      - Defined secure-by-default API security practices that passed rigorous VAPT audits
      - Mentored backend engineers in RESTful principles and advanced topics including documentation-first approach, API code generation, breaking changes detection, and API documentation (Redocly)
      - Led migration of legacy systems from EC2 to Kubernetes, implementing Kustomize for reproducible infrastructure
      - Implemented Kanban Flight Levels and advanced forecasting techniques, reducing cycle time from 35 days to 21 days

  - id: beno_lead
    achievements:
      - Wrote 10,000+ lines of code in Backend using Spring Boot (Java and Kotlin), establishing practices including Reactive Spring, TDD, Karate Testing, Documentation First, CI/CD, and Infrastructure as Code
      - Established company tech stack with Spring, Angular, MongoDB, Postgres (RDS), and Kubernetes (EKS), proving effective after 4 years

  - id: roamworks_arch
    achievements:
      - Designed and implemented microservices architecture using Spring (Java and Kotlin) and Netflix OSS

  - id: roamworks_bi
    achievements:
      - Migrated legacy ETL system (Smalltalk) to a new data warehousing stack using Apache Hop (a.k.a. Pentaho) supporting near realtime analytics over IoT data.

  - id: fujitsu
    achievements: []

skill_groups:
  - category: Technical
    skills: Backend Development (<span class="iconify" data-icon="devicon:spring"></span> Spring, Java, Kotlin), Cloud Architecture (<span class="iconify" data-icon="vscode-icons:file-type-aws"></span> AWS), Microservices, DevOps (<span class="iconify" data-icon="logos:kubernetes"></span> Kubernetes), SQL/NoSQL
  - category: Managerial
    skills: Technical Leadership, Solution Architecture, API Security, Release Management, Agile Methodologies
