jobs:
  - id: beno_cto
    achievements:
      - Led development of an LLM-powered chat feature from ideation to implementation using OpenAI and PromptFoo, resulting in a 10% increase in sales leads and 4% longer user sessions
      - Spearheaded research initiative deploying AI agents across the organization, including HR sourcing, QA regression testing, and release management automation, ensuring ethical implementation with proper oversight and bias mitigation
      - Directed company-wide AI adoption program tailored to different roles from executives to drivers, promoting responsible AI usage and establishing ethical guidelines for AI implementation across diverse business functions
      - Grew new leadership talent through effective 1-on-1s and objective performance reviews, resulting in the promotion of two engineers to Engineering Manager positions and one to a Technical Team Lead

  - id: beno_em
    achievements:
      - Grew the engineering department from 5 to 20 engineers while reducing annual turnover from 70% to 6% through strategic remote hiring
      - Enhanced agile methodology by implementing Kanban Flight Levels and advanced forecasting techniques using Cycle Time and Monte Carlo simulation
      - Implemented SaaS vendor selection strategy for OAuth, Analytics Governance, and Testing systems, reducing operational costs by 35% while ensuring seamless integration between enterprise and cloud systems

  - id: beno_lead
    achievements:
      - Migrated infrastructure from HostGator to <span class="iconify" data-icon="vscode-icons:file-type-aws"></span> AWS (EKS, S3, CloudFront) enabling distributed system architecture that resulted in a perfect SEO score and doubled web vitals performance
      - Established comprehensive code review process including peer reviews, automated static analysis, and CI/CD reports covering API Reference (OpenAPI), documentation (Markdown), architecture (Structurizr) and infrastructure-as-code (CloudFormation), resulting in high ability to use AI for co-editing code.

  - id: roamworks_arch
    achievements:
      - Migrated legacy application stack (Smalltalk) to a modern stack using <span class="iconify" data-icon="devicon:spring"></span> Spring for the backend, and <span class="iconify" data-icon="logos:angular-icon"></span> Angular for the frontend resulting in successful implementation for shipment container security IoT application.
      - Led the development of an ML-based fuel tank theft detection system using <span class="iconify" data-icon="vscode-icons:file-type-azure"></span>Azure Machine Learning, improving theft detection accuracy by 18%

  - id: roamworks_bi
    achievements: []

  - id: fujitsu
    achievements: []

skill_groups:
  - category: Technical
    skills: Full-stack Development (<span class="iconify" data-icon="vscode-icons:file-type-angular"></span> Angular, <span class="iconify" data-icon="devicon:spring"></span> Spring), <span class="iconify" data-icon="vscode-icons:file-type-aws"></span> AWS, AI/ML Integration, DevOps, Cloud Services, RESTful APIs
  - category: Managerial
    skills: Agile Methodologies, Team Leadership, Mentoring, Performance Management, Cross-functional Collaboration
