jobs:
  - id: beno_cto
    title: Senior Engineering Manager
    company: Beno Technologies
    city: Dubai
    start_date: 12/2022
    end_date: Present

  - id: beno_em
    title: Engineering Manager
    company: Beno Technologies
    city: Dubai
    start_date: 08/2021
    end_date: 12/2022

  - id: beno_lead
    title: Founding Engineer
    company: Beno Technologies
    city: Dubai
    start_date: 01/2020
    end_date: 08/2021

  - id: roamworks_arch
    title: Senior Full Stack Engineer
    company: Roamworks
    city: Dubai
    start_date: "2019"
    end_date: "2020"

  - id: roamworks_bi
    title: Full Stack Engineer
    company: Roamworks
    city: Dubai
    start_date: "2016"
    end_date: "2019"

  - id: fujitsu
    title: SAP Analytics Developer
    company: Fujitsu
    city: Abu Dhabi
    start_date: "2012"
    end_date: "2016"

education:
  - institution: University of Wollongong
    city: Dubai
    degree: Master of Science in Information Technology Management
    start_date: "2013"
    end_date: "2017"
  - institution: American University of Sharjah
    city: Sharjah
    degree: Bachelor of Science in Computer Engineering
    start_date: "2008"
    end_date: "2012"

skill_groups:
  - category: Technical
    skills: ""
  - category: Managerial
    skills: ""
